# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    esi: true
    secret: '%env(APP_SECRET)%'
    session: true
    assets:
        json_manifest_path: '%asset_manifest_path%'

    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
