services:
    nginx:
        image: nginx:latest
        ports:
            - "2501:80"
        volumes:
            - .:/project
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    php:
        build: config/docker/php
        image: chaostangent-php
        volumes:
            - .:/project

    pgsql:
        build: config/docker/pgsql
        image: chaostangent-pgsql
        environment:
            POSTGRES_DB: chaostangent
            POSTGRES_PASSWORD: chaostangent
            POSTGRES_USER: chaostangent
        ports:
            - "2502:5432"
        volumes:
            - database_data:/var/lib/postgresql:rw
            - ./config/docker/pgsql:/docker-entrypoint-initdb.d

    mailpit:
        image: axllent/mailpit:latest
        ports:
            - "2503:8025"

    mysql:
        image: mysql:8
        ports:
            - "2504:3306"
        environment:
            MYSQL_ROOT_PASSWORD: chaostangent

volumes:
    database_data:
