version: 2.1
jobs:
    install:
        working_directory: /tmp/chaostangent
        docker:
            - image: cimg/php:8.4-node
        steps:
            - checkout
            - run: sudo composer self-update
            - restore_cache:
                  keys:
                      - composer-v1-{{ checksum "composer.lock" }}
                      - composer-v1-
            - restore_cache:
                  keys:
                      - npm-v1-{{ checksum "package-lock.json" }}
                      - npm-v1-
            - run: composer install --no-interaction --no-progress --ignore-platform-req=ext-xsl --ignore-platform-req=ext-ffi
            - run: npm install
            - save_cache:
                  key: composer-v1-{{ checksum "composer.lock" }}
                  paths:
                      - vendor
            - save_cache:
                  key: npm-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            - persist_to_workspace:
                  root: /tmp/
                  paths:
                      - chaostangent

    coding-standards:
        working_directory: /tmp/chaostangent
        docker:
            - image: cimg/php:8.4
        steps:
            - attach_workspace:
                  at: /tmp
            - run: vendor/bin/phpcs -ns --colors

    static-analysis:
        working_directory: /tmp/chaostangent
        docker:
            - image: cimg/php:8.4
        steps:
            - attach_workspace:
                  at: /tmp
            - run: php -d memory_limit=512M vendor/bin/phpstan analyse -v

    test:
        working_directory: /tmp/chaostangent
        docker:
            - image: johnnoel/php:8.4
              environment:
                  APP_ENV: test
                  DATABASE_URL: postgresql://chaostangent:chaostangent@localhost/chaostangent_test?serverVersion=14&charset=utf8
            - image: cimg/postgres:17.5
              environment:
                  POSTGRES_USER: chaostangent
                  POSTGRES_PASSWORD: chaostangent
                  POSTGRES_DB: chaostangent_test
        steps:
            - attach_workspace:
                  at: /tmp
            - run: bin/phpunit --stop-on-failure --stop-on-error --log-junit junitreport.xml
            - store_test_results:
                  path: /tmp/chaostangent/junitreport.xml

    build-assets:
        working_directory: /tmp/chaostangent
        docker:
            - image: cimg/node:22.19.0
        steps:
            - attach_workspace:
                  at: /tmp
            - run: npm run prod
            - persist_to_workspace:
                  root: /tmp/
                  paths:
                      - chaostangent/public/assets

    build:
        working_directory: /tmp
        docker:
            - image: cimg/php:8.4
              environment:
                  APP_ENV: prod
        steps:
            - attach_workspace:
                    at: /tmp
            - run: composer install --working-dir /tmp/chaostangent --no-interaction --no-dev --no-progress --no-scripts --classmap-authoritative --ignore-platform-reqs
            - run: rm -rf /tmp/chaostangent/var/log/* /tmp/chaostangent/var/cache/*
            - run: tar cjf chaostangent.tar.bz2 -C /tmp/chaostangent .
            - store_artifacts:
                  path: /tmp/chaostangent.tar.bz2

    deploy:
        working_directory: /tmp/chaostangent
        docker:
            - image: johnnoel/php:8.4
        steps:
            - attach_workspace:
                  at: /tmp
            - add_ssh_keys:
                  fingerprints:
                        - "SHA256:KIxjSj6ztxfLVBI/vvWJ2GOOvLO0hifh85pL+VGYVJ0"
                        - "SHA256:sG8+EeLWdUcFzsO+WRNv8yOgC1cZ6V+iM2sWQXTx/KI"
            - run: echo "export EXTERNAL_IP=$(wget -qO- http://checkip.amazonaws.com/)" >> $BASH_ENV
            - run: hcloud firewall add-rule --description="CircleCI" --direction=in --source-ips="${EXTERNAL_IP}/32" --port=22 --protocol=tcp web-firewall
            - run: touch ~/.ssh/known_hosts && ssh-keyscan -H 91.98.226.139 >> ~/.ssh/known_hosts
            - run: vendor/bin/dep deploy -o "artifact_url=https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/latest/artifacts" -o "circle_ci_token=${CIRCLE_TOKEN}" all
            - run: hcloud firewall delete-rule --description="CircleCI" --direction=in --source-ips="${EXTERNAL_IP}/32" --port=22 --protocol=tcp web-firewall

workflows:
    version: 2
    install-and-test:
        jobs:
            - install
            - coding-standards:
                  requires:
                      - install
            - static-analysis:
                  requires:
                      - install
            - test:
                  requires:
                      - install
            - build-assets:
                  requires:
                      - install
                  filters:
                      branches:
                          only: main
            - build:
                  requires:
                      - coding-standards
                      - static-analysis
                      - test
                      - build-assets
                  filters:
                      branches:
                          only: main
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
