parameters:
    fallback_false: false
    resize_aliases:
        thumb: { w: 268 }
        lead: { w: 540 }
        poster: { w: 544 }
        square: { w: 320, h: 320 }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Comment\AkismetClient:
        arguments:
            $blog: https://chaostangent.com
            $apiKey: '%env(AKISMET_API_KEY)%'

    App\Comment\ChainDecider:
        arguments:
            $deciders:
                - '@App\Comment\HoneypotDecider'
                - '@App\Comment\TimeTakenDecider'
                - '@App\Comment\AkismetDecider'

    App\Comment\SpamDecider: '@App\Comment\ChainDecider'

    App\Extension\Twig\MediaExtension:
        arguments:
            $imageRepository: '@App\Image\CoreImageRepository'

    App\Form\DataTransformer\SignedDateTransformer:
        arguments:
            $key: '%env(APP_SECRET)%'

    App\Image\SourceFactory:
        arguments:
            $resizeAliases: '%resize_aliases%'

    App\Image\FileHandler:
        arguments:
            $mediaDirectory: '%env(MEDIA_LOCATION)%'
            $mediaUrl: '/media/'

    App\Image\GatheringImageRepository:
        arguments:
            $decoratedImageRepository: '@App\Image\CoreImageRepository'

    App\Post\ExportProcessor:
        arguments:
            $outputDirectory: '%kernel.project_dir%/content'

    App\Repository\FeatureRepository:
        arguments:
            $features:
                comments: '%env(default:fallback_false:bool:FEATURE_COMMENTS)%'
                search: '%env(default:fallback_false:bool:FEATURE_SEARCH)%'

    Intervention\Image\Interfaces\ImageManagerInterface:
        factory: [ 'Intervention\Image\ImageManager', 'withDriver' ]
        arguments:
            - 'Intervention\Image\Drivers\Imagick\Driver'

    Twig\Extension\StringLoaderExtension: ~

when@test:
    services:
        App\Comment\ChainDecider:
            arguments:
                $deciders:
                    - '@App\Comment\StaticDecider'

        App\Comment\StaticDecider:
            arguments:
                $isSpam: false
