parameters:
    fallback_false: false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Repository\FeatureRepository:
        arguments:
            $features:
                comments: '%env(default:fallback_false:bool:FEATURE_COMMENTS)%'
                search: '%env(default:fallback_false:bool:FEATURE_SEARCH)%'
